name = "subscription-queue-worker"
main = "src/index.js"
compatibility_date = "2023-01-01"

# D1 Database
[[d1_databases]]
binding = "DB"
database_name = "vbcloudflare-users"
database_id = "2f830aa3-01df-4c61-9ae2-e0023506a616"

# Cloudflare Queue
[[queues.consumers]]
queue = "subscription-queue"
max_batch_size = 10
max_batch_timeout = 30