name = "finance-queue-processor"
main = "src/api/queue-worker.js"
compatibility_date = "2023-07-10"

[[queues.consumers]]
queue = "finance-processing-queue"
max_batch_size = 10
max_batch_timeout = 5

[[d1_databases]]
binding = "DB"
database_name = "finance-tracker-db"
database_id = "78fc41c0-e6b5-40af-b3ea-b5c9ed0a5933"

[[r2_buckets]]
binding = "FILES"
bucket_name = "receipt-images"

[[kv_namespaces]]
binding = "SESSIONS"
id = "your-kv-namespace-id"  #
id = "9fe8a314739b43bdb3f30b104c484f7a"

