name = "auth-worker"
main = "src/index.js"
compatibility_date = "2023-01-01"

# KV Namespace binding - you'll create this in the Cloudflare dashboard
kv_namespaces = [
  { binding = "AUTH_TOKENS", id = "e8c6fc0f781346e9a01692d9d9fb2fd9" }
]

# D1 Database
[[d1_databases]]
binding = "DB"
database_name = "vbcloudflare-users"
database_id = "d42fe8bc-b1cd-42b0-af39-f9a457fb11e6"

# Environment variables
[vars]
JWT_SECRET = "e0f66bd50129f69e828f59997a5f5e61275be32276cdd749739f8eb4d93ae257" # Change this to a secure random string
TURNSTILE_SECRET_KEY = "0x4AAAAAABM4hRFOnt3BYnsGgejyndgieSc"

# Routes
routes = [
  { pattern = "auth-api.vbcloudflare.org/*", zone_name = "vbcloudflare.org" }
]